[package]
name = "inotify_toolkit_lib"
version = "0.0.0"
edition = "2021"
license = ""
homepage = "https://github.com/roma-glushko/inotify-toolkit"
repository = "https://github.com/roma-glushko/inotify-toolkit"
readme = "README.md"

[dependencies]
crossbeam-channel = "0.5.4"
notify = "6.0.0"
pyo3 = {version = "0.19.2", features = ["extension-module", "abi3-py37"]}

[lib]
name = "_inotify_toolkit_lib"
crate-type = ["cdylib"]
