[project]
name = "notifykit"
version = "0.0.1"
description = "A modern efficient Python toolkit for building applications that need to watch filesystem changes"
authors = [
    {name = "Roman Glushko", email = "roman.glushko.m@gmail.com"},
]
dependencies = []
requires-python = ">=3.11"
license = {text = "MIT"}

[project.urls]
Homepage = 'https://github.com/roma-glushko/notifykit'

[build-system]
requires = ['maturin>=0.14.16,<2']
build-backend = 'maturin'

[tool.maturin]
module-name = "notifykit._notifykit_lib"
bindings = 'pyo3'

[tool.pdm.dev-dependencies]
dev = [
    "pytest>=7.4.3",
    "mkdocs-material[imaging]>=9.4.8",
]
