[project]
name = "inotifykit"
version = "0.1.0"
description = "A modern efficient Python toolkit for building applications that need to watch filesystem changes"
authors = [
    {name = "Roman Glushko", email = "roman.glushko.m@gmail.com"},
]

dependencies = [
]

requires-python = ">=3.7"
readme = "README.md"
license = {text = "MIT"}

[build-system]
requires = ['maturin>=0.14.16,<2']
build-backend = 'maturin'

[tool.maturin]
module-name = "inotifykit._inotifykit_lib"
bindings = 'pyo3'
